version: 0.2

phases:
  install:
    commands:
      - "wget https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip"
      - "unzip terraform_1.5.7_linux_amd64.zip"
      - "mv terraform /usr/local/bin/"
  pre_build:
    commands:
      - "echo Initializing Terraform..."
      - "terraform init"
  build:
    commands:
      - "echo Running Terraform Plan..."
      - "terraform plan -out=tfplan"
artifacts:
  files:
    - tfplan
